// Generated by dts-bundle v0.7.3

declare module '@mobisys-internal/cordova-plugin-barcode-scanner' {
    global {
        interface CordovaPlugins {
            barcodeScanner: BarcodeScanner;
        }
    }
    
    export class BarcodeScanner {
            symbology: Readonly<{
                    UNKNOWN: number;
                    ALL_FORMATS: number;
                    CODE_128: number;
                    CODE_39: number;
                    CODE_93: number;
                    CODABAR: number;
                    DATA_MATRIX: number;
                    EAN_13: number;
                    EAN_8: number;
                    ITF: number;
                    QR_CODE: number;
                    UPC_A: number;
                    UPC_E: number;
                    PDF417: number;
                    AZTEC: number;
                    GS1_DATABAR: number;
                    MICRO_PDF417: number;
                    MICRO_QR_CODE: number;
            }>;
            scan(userOptions: IOptions, success: Action<IResult>, failure: Action<IError>): void;
    }
    
    export type IOptions = Partial<IConfig>;
    export type Action<T> = (arg: T) => unknown;
    export interface IConfig {
            symbologies: number;
            beepOnSuccess: boolean;
            vibrateOnSuccess: boolean;
            detectorSize: number;
            rotateCamera: boolean;
    }
    export interface IResult {
            value: string;
            symbology: string;
    }
    export interface IError {
            cancelled: boolean;
            message: string;
    }
}

